language: python

sudo: required

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install: sudo apt-get install libblas-dev liblapack-dev libatlas-dev python-opencv python-dev

install: "pip install -r requirements.txt"

script: nosetests
